### PR TITLE
fix data race in blake3's get_cpu_features()

### PR DESCRIPTION
**Pull request by arvidn**
details posted here: https://github.com/BLAKE3-team/BLAKE3/issues/220

### CODE REVIEW

**Comment by arvidn** [comment]
this is a bit more complex than I expected, since both MacOS and ManyLinux lack support for C11 threads functions (specifically, `call_once()`). This could be made to use the posix threading API. It seems MSVC is also lacking support for C11 threads though.

**Review by wjblanke — APPROVED** [review]
aok

**Comment by arvidn** [comment]
I'm not sure you should have landed this. CI was still half-red

**Comment by hoffmang9** [comment]
It hasn't been landed yet - just reviewed.

**Comment by arvidn** [comment]
this has been addressed upstream

**Pull request closed without merging**
