### PR TITLE
fetch-content blake3, add sse2 and neon optimizations

### PR DESCRIPTION
**Pull request by hoffmang9**
1. Use cmake fetch-content to get current BLAKE3 release.
2. Add neon asm optimizations to M1 and Linux aarch64.
3. Add sse2 support on Windows and Unix/MacOS x86_64.
4. Migrate away from custom Windows build in setup.py to cmake.

### CODE REVIEW

**Comment by hoffmang9** [comment]
Confirmed compiling and passing tests on M1 as well

**Comment by hoffmang9** [comment]
Hrm - https://github.com/BLAKE3-team/BLAKE3/blob/master/c/blake3_dispatch.c#L129

**Comment by hoffmang9** [comment]
Keep open.

**Comment by cmmarslender** [comment]
This work was completed in https://github.com/Chia-Network/chiapos/pull/402

**Pull request closed without merging**
