### PR TITLE
Use gulrak instead of filesystem, lower req to C++ 11

### PR DESCRIPTION
**Pull request by mariano54**
I have not confirmed that it works with Mojave, but this is what the compile options were like before filesystem was added.

### CODE REVIEW

**Comment by mariano54** [comment]
Do you know why it fails on windows @wjblanke ?

**Comment by hoffmang9** [comment]
image

**Comment by wjblanke** [comment]
we aren't using mingw anymore. you could try testing with visual studio and awjb branch

**Comment by hoffmang9** [comment]
But it did kill the mingw64 build for some reason.

**Comment by wjblanke** [comment]
Yup

**Pull request merged**
