### PR TITLE
Update to BLAKE3 version 0.3.7

### LINKED ISSUE #249: Why don't you use SSE2 & Neon Blake3 optimizations?
In latest Blake3 project you'll find the optimizations for the extensions SSE2 & Neon.
https://github.com/BLAKE3-team/BLAKE3/tree/master/c
Could you update your dependency to include latest Blake3 project?

### PR DESCRIPTION
**Pull request by elliottback**
Closes #249

### CODE REVIEW

**Comment by elliottback** [comment]
I was able to build this on my platform (x64 Intel Windows / MSVC), I think I need the runners to tell me if it is sane on the other platforms.

**Comment by tcinbis** [comment]
Works for me (x86 AMD Linux 5.10.34) :+1:

**Comment by arvidn** [comment]
it seems reasonable to update the blake3 implementation to take advantage of these optimizations.

However, given that we embed a copy of the blake3 implementation in this repo, rather than referencing it via a submodule, it makes it hard to audit updates like this. How can we validate that this source code actually corresponds to some official and trustworthy implementation of blake3?

There's also a more tangible issue, where the msvc build is failing with this patch: https://github.com/Chia-Network/chiapos/pull/251/checks?check_run_id=2645442250#step:8:288

The ARM build failure doesn't seem related to this patch directly though,

**Comment by elliottback** [comment]
> it seems reasonable to update the blake3 implementation to take advantage of these optimizations.
> 
> However, given that we embed a copy of the blake3 implementation in this repo, rather than referencing it via a submodule, it makes it hard to audit updates like this. How can we validate that this source code actually corresponds to some official and trustworthy implementation of blake3?

It might be better for sure to make it a submodule that would go fetch BLAKE3 at version XYZ in the build process.  That said, you can verify the files match https://github.com/BLAKE3-team/BLAKE3/releases/tag/0.3.7, but that's horrendously manual.

> There's also a more tangible issue, where the msvc build is failing with this patch: https://github.com/Chia-Network/chiapos/pull/251/checks?check_run_id=2645442250#step:8:288
> 
> The ARM build failure doesn't seem related to this patch directly though,

This is a draft I submitted to see how easy it is / is not to upgrade BLAKE3 in place.  Let me know if you want to me to continue to resolve the MSVC build issue, or if you think making it a submodule that pulls the BLAKE3 repo is better (and I will close this draft PR).

**Pull request closed without merging**
