### PR TITLE
If tmp2 and final files are in same filesystem, rename() not copy()

### PR DESCRIPTION
**Pull request by cross**
This avoids potentially painful copies of large files within the same filesystem.
To note:
 a) I'm a UNIX person, so I'm not sure if this will compile on Windows as coded.  Directions welcome.
 b) I didn't write a test for this, it appears all of the existing test only use files in the same directory.  Is the copy codepath in CreatePlotDisk() tested somewhere?

### CODE REVIEW

**Comment by cross** [comment]
This fixes #313 , waiting on workflows to test windows applicability.

**Comment by cross** [comment]
Can someone merge this?  Is anything else needed?

**Comment by hoffmang9** [comment]
This is likely to take a bit broader testing and that's the only hesitation. Right this moment there are other things at a higher priority. Should it test well on BSD/MacOS both flavors, three FSs etc.

**Comment by cross** [comment]
> This is likely to take a bit broader testing and that's the only hesitation. Right this moment there are other things at a higher priority. Should it test well on BSD/MacOS both flavors, three FSs etc.

Okay.  It's very old libc calls, so I'm sure all UNIX/Linux variants and Mac OS (>9) will work the same, but I do not criticize at all your wanting to test it fully.  Let me know if I can help.

**Comment by cross** [comment]
If I could get this in before the next chia-blockchain release, so its in there, that would be ideal.  Is there anything I can do to help testing this?  Just checking since it's been a few weeks here, happy to help if I can.

**Comment by cross** [comment]
Ping.  Sorry to be a noodge, but just wanted to make sure there's a plan to get the required testing done and get this merged.  Again, let me know if I can help.

**Comment by cross** [comment]
@rostislav @hoffmang9 Any status on this PR?

**Pull request merged**
